name: Deploy API NeoBarber 

on:
  push:
    branches: [ develop ]  # Ajusta esto según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Asegúrate de que esta versión sea compatible con Laravel 11
        #extensions: mbstring, ctype, fileinfo, openssl, pdo, tokenizer, xml # Añade extensiones necesarias

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      
    # - name: Run Tests
    #   run: php artisan test

    - name: Set up SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

    - name: Add Host Key
      run: echo "${{ secrets.VPS_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Deploy to Server
      env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_PATH: ${{ secrets.VPS_PATH }}
      run: |
        rsync -avz --exclude=".git" --exclude="node_modules" --exclude="storage/logs"  -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}
        ssh $SSH_USER@$SSH_HOST << 'EOF'
          export SSH_PATH=${{ secrets.VPS_PATH }}
          cd \$SSH_PATH
          # php artisan migrate
          # php artisan migrate: refresh --seed
          # php artisan migrate --force
          # php artisan db:seed --force
          # php artisan db:seed --force --class=DatabaseSeeder


          # Reiniciar colas de trabajo sin interrumpir procesos en ejecución
          php artisan queue:flush
          sleep 3
          php artisan queue:restart
          
          # Optimizar caché sin borrar datos importantes
          php artisan config:cache
          php artisan route:cache
          php artisan optimize
        EOF 